### ISSUE TITLE
Crash when I try load "Player Settings"

### ISSUE THREAD

**Issue by chachyyyy** [MediaModMC/MediaMod#11]
**Describe the bug**

**To Reproduce**
1. Go to 'MediaMod Settings'
2. Click on 'Player Settings'
3. See error

**Expected behavior**
I expected to see the menu for the player but received a crash with a NPE 

**Screenshots**

**Operating System**
What OS are you on? (Windows, macOS, Linux)
Windows

**Service causing this bug, if applicable**
What service were you using when the bug occurred? (Spotify, YouTube, SoundCloud, etc.)
N/A

**Additional context**
```
java.lang.NullPointerException: Rendering screen
	at me.conorthedev.mediamod.gui.PlayerOverlay.drawPlayer(PlayerOverlay.java:247)
	at me.conorthedev.mediamod.gui.GuiPlayerSettings.func_73863_a(GuiPlayerSettings.java:55)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:309)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1103)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at me.conorthedev.mediamod.gui.PlayerOverlay.drawPlayer(PlayerOverlay.java:247)
	at me.conorthedev.mediamod.gui.GuiPlayerSettings.func_73863_a(GuiPlayerSettings.java:55)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:309)
```

**Comment by AmpTheDev** [comment]
I'm working on it already, thanks for reporting!

**Comment by chachyyyy** [comment]
Okay, thank you the greatest developer, @AmpTheDev!

**Comment by ScottehBoeh** [comment]
I've just pushed a quick null check for that area of code. 👍

**Comment by chachyyyy** [comment]
Thanks Scotteh, the best developer!

**Comment by AmpTheDev** [comment]
oh god now my the pr im going to make with like 30 other bugs wont be able to merge

**Comment by AmpTheDev** [comment]
also @ScottehBoeh that won't fix it as the issue is rendering the preview when no song is playing. the correct behaviour should be it rendering the MediaMod logo when null and testing variable is true
